#################################
# Backend
#################################

backend = "xrender";
vsync = false;
use-damage = false;


#################################
# Shadows
#################################

shadow = true;
shadow-radius = 5;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.25;

shadow-exclude = [
  "class_g = 'Rofi'",
  "class_g = 'dmenu'"
];

#################################
# Fading
#################################

fading = false;

rounded-corners-exclude = [
	"class_g = 'Polybar'",
];

#################################
# Transparency
#################################

inactive-opacity = 0.95;
active-opacity = 0.99;
frame-opacity = 0.98;

inactive-opacity-override = false;

#################################
# Disable heavy features
#################################

corner-radius = 0;
blur-method = "none";
detect-rounded-corners = false;
detect-client-opacity = true;
